### ISSUE TITLE
Lack of unit tests

### ISSUE THREAD

**Issue by mcshaz** [DuSTman31/SHA-3#7]
Do you have a favourite unit testing framework? I can hopefully get the time to write a couple of simple tests. I note you are developing in visual studio- therefore maybe one of https://docs.microsoft.com/en-us/visualstudio/test/writing-unit-tests-for-c-cpp?view=vs-2019

**Comment by DuSTman31** [comment]
Hi. I'll be pleased to accept unit tests - it's something I've been thinking of adding, but haven't gotten around to evaluating the frameworks. Yes, I do the development work in visual studio but try to make it compile in linux as well - so the ability to run the tests cross platform is important. Looking at the link you sent, I'm leaning towards boost.test due to boost libraries being cross platform.

**Comment by mcshaz** [comment]
I have written some very simple tests of the SHA-3 algorithm (256 & 512 hash width) in boost. They are passing:

https://github.com/mcshaz/SHA-3/blob/master/KeccakTests/KeccakTests.cpp

I haven't put a pull request, as it involved creating a separate test project, and therefore I moved the existing code into a separate folder. I also moved the main (console/entry) function into commandParser.cpp, as this allowed writing the tests without having 2 main functions.

**Comment by DuSTman31** [comment]
Looks good :)
I didn't initially commit the root solution directory and the .sln file because there wasn't anything else there but the keccak code that people would be interested in. I'll see about re-arranging the repo.
I've also got a small external tool that tests the NIST standard test vectors for byte oriented implementations (though I haven't finished the implementation of the monte carlo tests), now I'm wondering if it'd be better to integrate those tests into this framework.

**Comment by mcshaz** [comment]
I have rearranged into a more standard directory structure in my master fork. let me know if you want a pull request.
